/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CategoriaController;
import Controller.SubastaController;
import Model.Categoria;
import Model.SubCategoria;
import Model.Subasta;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class ListadoSubastas extends javax.swing.JFrame {

    /**
     * Creates new form ListadoSubastas
     */
    private DefaultComboBoxModel modeloCat2;
    private DefaultComboBoxModel modeloSubcat2;
    private DefaultTableModel modelo;
    private CategoriaController categoriaController;
    private SubastaController subastaController;

    public ListadoSubastas() throws SQLException {
        initComponents();
        categoriaController = new CategoriaController();
        subastaController = new SubastaController();
        modeloCat2 = new DefaultComboBoxModel();
        modeloCat2 = (DefaultComboBoxModel) cbxCategoria2.getModel();
        modeloSubcat2 = new DefaultComboBoxModel();
        modeloSubcat2 = (DefaultComboBoxModel) cbxSubcategoria2.getModel();
        modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) jTableSubastas.getModel();
        llenarComboCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListarSubasta = new javax.swing.JPanel();
        jPanelListado = new javax.swing.JPanel();
        btnDetallesSubasta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSubastas = new javax.swing.JTable();
        btnHistorial = new javax.swing.JButton();
        btnPujar = new javax.swing.JButton();
        lblCategoria1 = new javax.swing.JLabel();
        lblSubCategoria1 = new javax.swing.JLabel();
        cbxCategoria2 = new javax.swing.JComboBox<>();
        cbxSubcategoria2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelListado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de subastas activas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnDetallesSubasta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDetallesSubasta.setText("Detalles");
        btnDetallesSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesSubastaActionPerformed(evt);
            }
        });

        jTableSubastas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio", "Categoría", "Subcategoría", "Vendedor"
            }
        ));
        jScrollPane1.setViewportView(jTableSubastas);

        btnHistorial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnHistorial.setText("Historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        btnPujar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPujar.setText("PUJAR");
        btnPujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPujarActionPerformed(evt);
            }
        });

        lblCategoria1.setText("Categoria");

        lblSubCategoria1.setText("SubCategoria");

        cbxCategoria2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCategoria2ItemStateChanged(evt);
            }
        });
        cbxCategoria2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxCategoria2FocusLost(evt);
            }
        });
        cbxCategoria2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxCategoria2MouseClicked(evt);
            }
        });
        cbxCategoria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoria2ActionPerformed(evt);
            }
        });

        cbxSubcategoria2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSubcategoria2ItemStateChanged(evt);
            }
        });
        cbxSubcategoria2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxSubcategoria2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelListadoLayout = new javax.swing.GroupLayout(jPanelListado);
        jPanelListado.setLayout(jPanelListadoLayout);
        jPanelListadoLayout.setHorizontalGroup(
            jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubCategoria1)
                    .addComponent(lblCategoria1))
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListadoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(cbxCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListadoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxSubcategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListadoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnDetallesSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)
                        .addComponent(btnPujar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanelListadoLayout.setVerticalGroup(
            jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetallesSubasta)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPujar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(jPanelListadoLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria1))
                .addGap(46, 46, 46)
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSubcategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubCategoria1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelListarSubastaLayout = new javax.swing.GroupLayout(jPanelListarSubasta);
        jPanelListarSubasta.setLayout(jPanelListarSubastaLayout);
        jPanelListarSubastaLayout.setHorizontalGroup(
            jPanelListarSubastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarSubastaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelListado, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelListarSubastaLayout.setVerticalGroup(
            jPanelListarSubastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarSubastaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1178, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelListarSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelListarSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetallesSubastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesSubastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetallesSubastaActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnPujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPujarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPujarActionPerformed

    private void cbxCategoria2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCategoria2ItemStateChanged
        /**
         * Funcion: Refresca el cbx con los objetos subcategoria
         * correspondientes segun la categoria seleccionada al hacer click en el
         * cbx de categorias. Entradas: Ninguna Salidas: Ninguna
         */
        Categoria cat = (Categoria) modeloCat2.getSelectedItem();
        System.out.println(cat.getId());
        createSubCat2(cat);
    }//GEN-LAST:event_cbxCategoria2ItemStateChanged

    private void cbxCategoria2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxCategoria2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoria2FocusLost

    private void cbxCategoria2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxCategoria2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoria2MouseClicked

    private void cbxCategoria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoria2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoria2ActionPerformed

    private void cbxSubcategoria2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSubcategoria2ItemStateChanged
        SubCategoria subcat = (SubCategoria) modeloSubcat2.getSelectedItem();
        //llenarJTable(subcat.getId());  //Ponerlo en otra funcion
        //System.out.println(subcat.getId());

    }//GEN-LAST:event_cbxSubcategoria2ItemStateChanged

    private void cbxSubcategoria2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxSubcategoria2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSubcategoria2MouseClicked

    /**
     * Funcion: Llenar el cbx con objetos de tipo categoria Entradas: Ninguna
     * Salidas: Ninguna
     */
    public void llenarComboCategorias() {

        ArrayList<Categoria> lista = categoriaController.devolverCategorias();
        for (int i = 0; i < lista.size(); i++) {
            modeloCat2.addElement(lista.get(i));
            cbxCategoria2.setModel(modeloCat2);
        }

    }

    /**
     * Funcion: Recibe una categoria y de ella despliega sus subcategorias en el
     * modeloSubCat2
     *
     * @param cat
     */
    public void createSubCat2(Categoria cat) {
        ArrayList<SubCategoria> lista = cat.getSubcategorias();
        modeloSubcat2.removeAllElements();
        for (int i = 0; i < lista.size(); i++) {
            modeloSubcat2.addElement(lista.get(i));
        }
        cbxSubcategoria2.setModel(modeloSubcat2);
    }

    /**
     * Funcion: Segun una sucategoria, muestra las subastas que coinciden
     *
     * @param idSubcat
     */
    private void llenarJTable(double idSubcat) {
        ArrayList<Subasta> lista = subastaController.listarSubastas(idSubcat);
        System.out.println(lista);
        if (!lista.isEmpty()){
            for (int i = 0; i < lista.size(); i++) {
                modelo.addRow(new Object[]{lista.get(i)});  //Poner acá los datos en orden a poner en la fila
                jTableSubastas.setModel(modelo);
            }
        }
        else{
               JOptionPane.showMessageDialog(null, "No hay subastas de esta subcategoria");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListadoSubastas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ListadoSubastas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetallesSubasta;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnPujar;
    private javax.swing.JComboBox<String> cbxCategoria2;
    private javax.swing.JComboBox<String> cbxSubcategoria2;
    private javax.swing.JPanel jPanelListado;
    private javax.swing.JPanel jPanelListarSubasta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSubastas;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblSubCategoria1;
    // End of variables declaration//GEN-END:variables
}
