/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CategoriaController;
import Controller.SubastaController;
import Controller.UsuarioController;
import Model.Categoria;
import Model.SubCategoria;
import Model.Subasta;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public final class ListaSubastas extends javax.swing.JFrame {

    private DefaultComboBoxModel modeloCat3;
    private DefaultComboBoxModel modeloSubcat3;
    private DefaultTableModel modelo;
    private CategoriaController categoriaController;
    private SubastaController subastaController;
    private UsuarioController userController;
    private ArrayList<Subasta> listaSubastas;
    private int selectedRow;
    
    public ListaSubastas() throws SQLException {
        initComponents();
        btnPujar.setEnabled(false);
        categoriaController = new CategoriaController();
        subastaController = new SubastaController();
        modeloCat3 =  new DefaultComboBoxModel();
        modeloCat3 = (DefaultComboBoxModel)cbxCategoria3.getModel();
        modeloSubcat3 =  new DefaultComboBoxModel();
        modeloSubcat3 = (DefaultComboBoxModel)cbxSubcategoria3.getModel();
        modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) jTableSubastas.getModel();
        userController = new UsuarioController();
        llenarComboCategorias();
        mostrarObjetos();
        selectedRow = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListarSubasta = new javax.swing.JPanel();
        jPanelListado = new javax.swing.JPanel();
        btnHistorialVendedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSubastas = new javax.swing.JTable();
        btnHistorialPujas = new javax.swing.JButton();
        btnPujar = new javax.swing.JButton();
        lblCategoria1 = new javax.swing.JLabel();
        lblSubCategoria1 = new javax.swing.JLabel();
        cbxCategoria3 = new javax.swing.JComboBox<>();
        cbxSubcategoria3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelListado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de subastas activas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnHistorialVendedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnHistorialVendedor.setText("Ver historial del vendedor");
        btnHistorialVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialVendedorActionPerformed(evt);
            }
        });

        jTableSubastas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Subcategoria", "Precio Inicial", "Precio final", "Detalles", "Fecha inicio", "Fecha fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSubastas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSubastasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSubastas);

        btnHistorialPujas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnHistorialPujas.setText("Ver historial pujas");
        btnHistorialPujas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialPujasActionPerformed(evt);
            }
        });

        btnPujar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPujar.setText("Pujar en esta subasta");
        btnPujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPujarActionPerformed(evt);
            }
        });

        lblCategoria1.setText("Categoria");

        lblSubCategoria1.setText("SubCategoria");

        cbxCategoria3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCategoria3ItemStateChanged(evt);
            }
        });
        cbxCategoria3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxCategoria3FocusLost(evt);
            }
        });
        cbxCategoria3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxCategoria3MouseClicked(evt);
            }
        });
        cbxCategoria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoria3ActionPerformed(evt);
            }
        });

        cbxSubcategoria3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSubcategoria3ItemStateChanged(evt);
            }
        });
        cbxSubcategoria3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxSubcategoria3MouseClicked(evt);
            }
        });
        cbxSubcategoria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSubcategoria3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListadoLayout = new javax.swing.GroupLayout(jPanelListado);
        jPanelListado.setLayout(jPanelListadoLayout);
        jPanelListadoLayout.setHorizontalGroup(
            jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListadoLayout.createSequentialGroup()
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListadoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubCategoria1)
                            .addComponent(lblCategoria1))
                        .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelListadoLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(cbxCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListadoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxSubcategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))
                    .addGroup(jPanelListadoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnPujar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListadoLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnHistorialVendedor)
                        .addGap(18, 18, 18)
                        .addComponent(btnHistorialPujas))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanelListadoLayout.setVerticalGroup(
            jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoLayout.createSequentialGroup()
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelListadoLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria1))
                        .addGap(46, 46, 46)
                        .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxSubcategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubCategoria1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPujar)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelListadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHistorialPujas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistorialVendedor))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanelListarSubastaLayout = new javax.swing.GroupLayout(jPanelListarSubasta);
        jPanelListarSubasta.setLayout(jPanelListarSubastaLayout);
        jPanelListarSubastaLayout.setHorizontalGroup(
            jPanelListarSubastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarSubastaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelListarSubastaLayout.setVerticalGroup(
            jPanelListarSubastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarSubastaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelListarSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelListarSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistorialVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialVendedorActionPerformed
        if (!(selectedRow==-1)){
            try {
                double idVendedor = listaSubastas.get(selectedRow).getUsuarioId();
                VentanaHistorialVendedor ventanaVendedor = new VentanaHistorialVendedor(idVendedor);
                ventanaVendedor.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(ListaSubastas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione una subasta para ver su vendedor");
        }
    }//GEN-LAST:event_btnHistorialVendedorActionPerformed

    private void btnHistorialPujasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialPujasActionPerformed

        if (!(selectedRow==-1)){
            try {
                double idSubasta = listaSubastas.get(selectedRow).getId();
                VentanaHistorialPujas ventanaHistorialPujas = new VentanaHistorialPujas(idSubasta);
                ventanaHistorialPujas.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(ListaSubastas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione una subasta");
        }
        
    }//GEN-LAST:event_btnHistorialPujasActionPerformed

    private void btnPujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPujarActionPerformed
        double idSubasta = listaSubastas.get(selectedRow).getId();
        try {
            VentanaPujar ventanaPujar = new VentanaPujar(idSubasta);
            ventanaPujar.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ListaSubastas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnPujarActionPerformed

    private void cbxCategoria3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCategoria3ItemStateChanged
        /**
        * Funcion: Refresca el cbx con los objetos subcategoria correspondientes segun la categoria seleccionada al
        * hacer click en el cbx de categorias.
        * Entradas: Ninguna
        * Salidas: Ninguna
        */
        Categoria cat = (Categoria) modeloCat3.getSelectedItem();
        System.out.println(cat.getId());
        createSubCat2(cat);
    }//GEN-LAST:event_cbxCategoria3ItemStateChanged

    private void cbxCategoria3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxCategoria3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoria3FocusLost

    private void cbxCategoria3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxCategoria3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoria3MouseClicked

    private void cbxCategoria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoria3ActionPerformed

    private void cbxSubcategoria3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSubcategoria3ItemStateChanged
        SubCategoria subcat = (SubCategoria) modeloSubcat3.getSelectedItem();
        if(modeloSubcat3.getSelectedItem() != null){llenarJTable(subcat.getId());}
        else{vaciarJTable();}
        
    }//GEN-LAST:event_cbxSubcategoria3ItemStateChanged

    private void cbxSubcategoria3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxSubcategoria3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSubcategoria3MouseClicked

    private void jTableSubastasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSubastasMouseClicked
        btnPujar.setEnabled(true);
        int posicion = jTableSubastas.getSelectedRow();
        selectedRow = posicion;
    }//GEN-LAST:event_jTableSubastasMouseClicked

    private void cbxSubcategoria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSubcategoria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSubcategoria3ActionPerformed

    
    
    
    public void llenarComboCategorias(){
        /**
         * Funcion: Llenar el cbx con objetos de tipo categoria
         * Entradas: Ninguna
         * Salidas: Ninguna
         */
        ArrayList<Categoria> lista = categoriaController.devolverCategorias();

        for (int i = 0; i < lista.size(); i++){
            modeloCat3.addElement(lista.get(i));
            cbxCategoria3.setModel(modeloCat3);
        }
       
    }
    
    public void createSubCat2(Categoria cat){
        
        ArrayList<SubCategoria> lista = cat.getSubcategorias();
        modeloSubcat3.removeAllElements();
        for (int i = 0; i < lista.size(); i++){
                modeloSubcat3.addElement(lista.get(i));
            }
        cbxSubcategoria3.setModel(modeloSubcat3);
    }
    
    
    private void vaciarJTable(){
    
        DefaultTableModel temp = (DefaultTableModel) jTableSubastas.getModel();
        temp.setRowCount(0);
    
    }
    
    private void llenarJTable(double idSubcat){
        
        vaciarJTable();
        
        listaSubastas = subastaController.listarSubastas(idSubcat);
        if(idSubcat>0){  //Validar aqui bien
            if(!listaSubastas.isEmpty()){
                for (int i = 0; i < listaSubastas.size(); i++){

                        modelo.addRow(new Object[]{listaSubastas.get(i).getNombreUsuario(),listaSubastas.get(i).getNombreSubcat(),
                         listaSubastas.get(i).getPrecioInicial(),listaSubastas.get(i).getPrecioFinal(),listaSubastas.get(i).getDetallesEntrega(),
                        listaSubastas.get(i).getFechaInicio(),listaSubastas.get(i).getFechaFin()});  
                        jTableSubastas.setModel(modelo);
                }       
            }
            else{
                JOptionPane.showMessageDialog(null, "No hay subastas con esa categoría");
            }
        }
    }
    
    
    public void mostrarObjetos(){
        
        if(userController.getTipoUsuario()){
            btnPujar.setVisible(false);
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ListaSubastas().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(ListaSubastas.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorialPujas;
    private javax.swing.JButton btnHistorialVendedor;
    private javax.swing.JButton btnPujar;
    private javax.swing.JComboBox<String> cbxCategoria3;
    private javax.swing.JComboBox<String> cbxSubcategoria3;
    private javax.swing.JPanel jPanelListado;
    private javax.swing.JPanel jPanelListarSubasta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSubastas;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblSubCategoria1;
    // End of variables declaration//GEN-END:variables

    private VentanaHistorialVendedor VentanaHistorialVendedor() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
