/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.PujaController;
import Controller.UsuarioController;
import Model.Puja;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class VentanaPujar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPujar
     */
    
    private PujaController pujaController;
    private double idSubasta;
    private ArrayList<Puja> listaPuja;
    private DefaultTableModel modelo;
    
    public VentanaPujar(double idSubasta) throws SQLException {
        initComponents();
        this.idSubasta = idSubasta;
        pujaController = new PujaController();
        modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) jTablePujas.getModel();
        llenarJTable(idSubasta);
    }

    private VentanaPujar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePujas = new javax.swing.JTable();
        lblTituloTiempo = new javax.swing.JLabel();
        lblTimeleft = new javax.swing.JLabel();
        lblCantPujar = new javax.swing.JLabel();
        txtCantPujar = new javax.swing.JTextField();
        btnPujar = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTablePujas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Persona"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePujas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablePujas);
        if (jTablePujas.getColumnModel().getColumnCount() > 0) {
            jTablePujas.getColumnModel().getColumn(0).setResizable(false);
            jTablePujas.getColumnModel().getColumn(1).setResizable(false);
        }

        lblTituloTiempo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloTiempo.setText("Tiempo restante:");

        lblTimeleft.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblCantPujar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCantPujar.setText("Cantidad a pujar: ");

        txtCantPujar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantPujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantPujarActionPerformed(evt);
            }
        });

        btnPujar.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnPujar.setText("Pujar");
        btnPujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPujarActionPerformed(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnPujar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantPujar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCantPujar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTimeleft, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTimeleft, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblCantPujar)
                        .addGap(28, 28, 28)
                        .addComponent(txtCantPujar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnPujar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPujarActionPerformed

        try {
            UsuarioController uc = new UsuarioController();
            double idUser = uc.getUsuario().getId();
            double precio = Double.parseDouble(txtCantPujar.getText());
            if(pujaController.insertarPuja(idUser,idSubasta,precio)){
                JOptionPane.showMessageDialog(null, "Puja realizada");
            }
            else{
                JOptionPane.showMessageDialog(null, "La puja debe ser de un monto mayor a "+String.valueOf(pujaController.precioNecesarioPuja(idSubasta, precio)));
            }
            llenarJTable(idSubasta);
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(VentanaPujar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPujarActionPerformed

    private void txtCantPujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantPujarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantPujarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPujar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPujar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPujar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPujar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPujar().setVisible(true);
            }
        });
    }
    
    
    private void llenarJTable(double idSubcat){
        
        vaciarJTable();
        listaPuja = pujaController.listarPujas(idSubasta);
        if(!listaPuja.isEmpty()){
            for (int i = 0; i < listaPuja.size(); i++){
                    
                    modelo.addRow(new Object[]{listaPuja.get(i).getPrecio(),listaPuja.get(i).getNombreComprador()});  
                    jTablePujas.setModel(modelo);
            }       
        }
        else{
            JOptionPane.showMessageDialog(null, "No hay pujas en esta subasta");
        }
    }
    
    private void vaciarJTable(){
    
        DefaultTableModel temp = (DefaultTableModel) jTablePujas.getModel();
        temp.setRowCount(0);
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPujar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePujas;
    private javax.swing.JLabel lblCantPujar;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTimeleft;
    private javax.swing.JLabel lblTituloTiempo;
    private javax.swing.JTextField txtCantPujar;
    // End of variables declaration//GEN-END:variables
}
