/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.PujaController;
import Model.Puja;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class VentanaHistorialPujas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaHistorialPujas
     */
    private double idSubasta;
    private DefaultTableModel modelo;
    private PujaController pujaController;
    private ArrayList<Puja> listaPujas;
    private int selectedRow;
    
    public VentanaHistorialPujas(double idSubasta) throws SQLException {
        initComponents();
        System.out.println(idSubasta);
        modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) jTableHPujas.getModel();
        this.idSubasta = idSubasta;
        pujaController = new PujaController();
        llenarJTable();
    }

    private VentanaHistorialPujas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListado = new javax.swing.JPanel();
        btnHistorialComprador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHPujas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelListado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de pujas de la subasta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnHistorialComprador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnHistorialComprador.setText("Ver historial del comprador");
        btnHistorialComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialCompradorActionPerformed(evt);
            }
        });

        jTableHPujas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Precio", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHPujas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHPujasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHPujas);

        javax.swing.GroupLayout jPanelListadoLayout = new javax.swing.GroupLayout(jPanelListado);
        jPanelListado.setLayout(jPanelListadoLayout);
        jPanelListadoLayout.setHorizontalGroup(
            jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListadoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelListadoLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnHistorialComprador)))
                .addGap(364, 364, 364))
        );
        jPanelListadoLayout.setVerticalGroup(
            jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHistorialComprador)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistorialCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialCompradorActionPerformed
        double idComprador = listaPujas.get(selectedRow).getCompradorId();
        VentanaHistorialComprador ventanaComprador = new VentanaHistorialComprador(idComprador);
        ventanaComprador.setVisible(true);
    }//GEN-LAST:event_btnHistorialCompradorActionPerformed

    private void jTableHPujasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHPujasMouseClicked
        int posicion = jTableHPujas.getSelectedRow();
        selectedRow = posicion;
    }//GEN-LAST:event_jTableHPujasMouseClicked

    
    private void llenarJTable(){
        vaciarJTable();
        listaPujas = pujaController.listarPujas(idSubasta);
       
        if(!listaPujas.isEmpty()){
            for (int i = 0; i < listaPujas.size(); i++){ 
                    modelo.addRow(new Object[]{listaPujas.get(i).getNombreComprador(),listaPujas.get(i).getPrecio(),
                    listaPujas.get(i).getFecha()});  
                    jTableHPujas.setModel(modelo);
            }       
        }
        else{
            JOptionPane.showMessageDialog(null, "No hay pujas para esta subasta");
        }
       
    }
    
    private void vaciarJTable(){
    
        DefaultTableModel temp = (DefaultTableModel) jTableHPujas.getModel();
        temp.setRowCount(0);
    
    }
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialPujas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialPujas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialPujas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialPujas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaHistorialPujas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorialComprador;
    private javax.swing.JPanel jPanelListado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHPujas;
    // End of variables declaration//GEN-END:variables
}
