

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE ROLE Usuario NOT IDENTIFIED;
CREATE ROLE Administrador NOT IDENTIFIED;

--ADMI
GRANT CREATE SESSION TO Administrador;
GRANT DBA TO Administrador;
--NORMAL

GRANT CREATE SESSION TO Usuario;
GRANT EXECUTE ON Natalia.SP_SELECTUSERS TO Usuario;
GRANT EXECUTE ON Natalia.SP_INSERTAUCTION TO Usuario;
GRANT EXECUTE ON Natalia.SP_INSERTIMAGE TO Usuario;
GRANT EXECUTE ON Natalia.SP_INSERTPUJA TO Usuario;
GRANT EXECUTE ON Natalia.SP_SELECTAUCTION TO Usuario;
GRANT EXECUTE ON Natalia.SP_SELECTAUCTIONBYID TO Usuario;
GRANT EXECUTE ON Natalia.SP_SELECTCATEGORIES TO Usuario;
GRANT EXECUTE ON Natalia.SP_SELECTHISTORIALCOMPRADOR TO Usuario;
GRANT EXECUTE ON Natalia.SP_SELECTHISTORIALVENDEDOR TO Usuario;
GRANT EXECUTE ON Natalia.SP_SELECTPARAMETERS TO Usuario;
GRANT EXECUTE ON Natalia.SP_SELECTPUJAS TO Usuario;
GRANT EXECUTE ON Natalia.SP_SELECTSUBCATEGORIES TO Usuario;


CREATE USER nata IDENTIFIED BY nata;
GRANT Usuario TO nata;

DROP ROLE Usuario









--Ejemplo
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE ROLE CLIENTE NOT IDENTIFIED;

CREATE USER ESTUDIANTE IDENTIFIED BY asd;  --en el sp
GRANT CLIENTE TO ESTUDIANTE;   --EN EL SP

GRANT CREATE SESSION TO CLIENTE;
GRANT EXECUTE ON SP_SELECTUSERS TO CLIENTE;