create or replace NONEDITIONABLE PROCEDURE SP_SelectMiHistoComp(
       miID IN HISTORIALVENDEDOR.IDCOMPRADOR%TYPE,
       cursor OUT SYS_REFCURSOR)
       
IS
BEGIN
    OPEN cursor FOR
    SELECT 
        HC."IDCOMPRADOR"
       ,UV."NOMBRE"
       ,HC."IDVENDEDOR"
       ,UC."NOMBRE"
       ,HC."IDSUBASTA"
       ,S."PRECIOINICIAL"
       ,S."PRECIOFINAL"
       ,HC."COMENTARIO"
       ,HC."CALIFICACION"
       ,S.FECHAFIN

   FROM HISTORIALCOMPRADOR HC INNER JOIN USUARIO UV ON HC.IDCOMPRADOR = UV.ID 
   INNER JOIN USUARIO UC ON HC.IDCOMPRADOR = UC.ID
   INNER JOIN SUBASTA S ON HC.IDSUBASTA = S.ID

   WHERE HC.IDCOMPRADOR = miID;

COMMIT;
END;