

CREATE OR REPLACE TRIGGER TR_UpdateBeforeInsertPujas
BEFORE INSERT ON PUJAS

    FOR EACH ROW
        DECLARE DECIMAL PRECIOMEJORFINAL;
        SELECT S.PRECIOMEJOR INTO PRECIOMEJORFINAL FROM SUBASTA S WHERE S.SUBASTAID = :NEW.SUBASTAID;
        BEGIN
        
        IF (:NEW.PRECIO> PRECIOMEJORFINAL) THEN
            EXECUTE SP_UpdateAuction(:NEW.PRECIO,:NEW.COMPRADORID,:NEW.SUBASTAID);
        END IF;
  

 END TR_UpdateBeforeInsertPujas;

--  que desgracia